### ISSUE TITLE
Request if may i

### ISSUE THREAD

**Issue by rpdroky** [Asd-g/AviSynth-SangNom2#3]
Could you include fturn in this plugin? the only problem is the last version was 32bit
http://avisynth.nl/index.php/FTurn

Cheers !

**Comment by Asd-g** [comment]
Hi,
Check the note here - http://avisynth.nl/index.php/FTurn
For AviSynth+ the plugin does not give any benefit.

**Comment by rpdroky** [comment]
> 
> 
> Hi,
> Check the note here - http://avisynth.nl/index.php/FTurn
> For AviSynth+ the plugin does not give any benefit.

My bad and my humble apologies , somehow i missed that
